package set

var SetName = map[string]string{
	"Phantasmal Flames":       "094",
	"Mega Evolution Base Set": "132",
	"Black Bolt":              "086",
	"White Flare":             "086",
	"Destined Rivals":         "182",
	"Journey Together":        "159",
	"Prismatic Evolutions":    "131",
	"Surging Sparks":          "191",
	"Stellar Crown":           "142",
	"Shrouded Fable":          "064",
	"Twilight Masquerade":     "167",
	"Temporal Forces":         "162",
	"Paldean Fates":           "091",
	"Paradox Rift":            "182",
	"Scarlet & Violet 151":    "165",
	"Obsidian Flames":         "197",
	"Pladea Evolved":          "193",
	"Scarlet & Violet":        "198",
	"SV Black Star Promos":    "",
	// Sword and Shield
	"Crown Zenith":           "159",
	"Silver Tempest":         "195",
	"Lost Origin":            "196",
	"Pokemon Go":             "078",
	"Astral Radiance":        "189",
	"Brilliant Stars":        "172",
	"Fusion Strike":          "264",
	"Celebrations":           "",
	"Evolving Skies":         "203",
	"Chilling Reign":         "198",
	"Battle Styles":          "163",
	"Shining Fates":          "072",
	"Vivid Voltage":          "185",
	"Champion's Path":        "073",
	"Darkness Ablaze":        "189",
	"Rebel Clash":            "192",
	"Sword & Shield":         "202",
	"SWSH Black Star Promos": "",
	// Sun & Moon
	"Cosmic Eclipse":       "236",
	"Hidden Fates":         "68",
	"Unified Minds":        "236",
	"Unbroken Bonds":       "214",
	"Detective Pikachu":    "18",
	"Team Up":              "181",
	"Lost Thunder":         "214",
	"Dragon Majesty":       "70",
	"Celestial Storm":      "168",
	"Forbidden Light":      "131",
	"Ultra Prism":          "156",
	"Crimson Invasion":     "111",
	"Shining Legends":      "73",
	"Burning Shadows":      "147",
	"Guardians Rising":     "145",
	"Sun & Moon":           "149",
	"SM Black Star Promos": "",
	// XY
	"Evolutions":              "108",
	"Steam Siege":             "114",
	"World Championship Deck": "",
	"ex Starter Set Steven's Beldum & Metagross ex": "018",
	"Fates Collide":        "124",
	"Generations":          "83",
	"BREAKpoint":           "122",
	"BREAKthrough":         "162",
	"Ancient Origins":      "98",
	"Roaring Skies":        "108",
	"Double Crisis":        "34",
	"Primal Clash":         "160",
	"Phantom Forces":       "119",
	"Furious Fists":        "111",
	"Flashfire":            "106",
	"XY Base Set":          "146",
	"XY Black Star Promos": "",
	// Black & White
	"Legendary Treasures":  "113",
	"Plasma Blast":         "101",
	"Plasma Freeze":        "116",
	"Plasma Storm":         "135",
	"Boundaries Crossed":   "149",
	"Dragon Vault":         "20",
	"Dragons Exalted":      "124",
	"Dark Explorers":       "108",
	"Next Destinies":       "99",
	"Noble Victories":      "101",
	"Emerging Powers":      "98",
	"Black & White":        "114",
	"BW Black Star Promos": "",
	// Call of Legends
	"Call of Legends": "",
	// HeartGold & SoulSilver
	"Triumphant":             "102",
	"Undaunted":              "90",
	"Unleashed":              "95",
	"HeartGold & SoulSilver": "123",
	"HGSS Black Star Promos": "",
	// Platinum
	"Arceus":          "99",
	"Supreme Victors": "147",
	"Rising Rivals":   "111",
	"Platinum":        "127",
	// Pop Series
	"Pop Series 9": "17",
	"Pop Series 8": "17",
	"Pop Series 7": "17",
	"Pop Series 6": "17",
	"Pop Series 5": "17",
	"Pop Series 4": "17",
	"Pop Series 3": "17",
	"Pop Series 2": "17",
	"Pop Series 1": "17",
	// Diamond & Pearl
	"Stormfront":           "100",
	"Legends Awakened":     "146",
	"Majestic Dawn":        "100",
	"Great Encounters":     "106",
	"Secret Wonders":       "132",
	"Mysterious Treasures": "123",
	"Diamond & Pearl":      "130",
	"DP Black Star Promo":  "",
	// EX Ruby & Sapphire
	"EX Power Keepers":           "108",
	"EX Dragon Frontiers":        "101",
	"EX Crystal Guardians":       "100",
	"EX Holon Phantoms":          "110",
	"EX Legend Maker":            "92",
	"EX Delta Species":           "113",
	"EX Unseen Forces":           "28",
	"EX Emerald":                 "106",
	"EX Deoxys":                  "107",
	"EX Team Rocket Returns":     "109",
	"EX FireRed & LeafGreen":     "112",
	"EX Hidden Legends":          "101",
	"EX Team Magma vs Team Aqua": "95",
	"EX Dragon":                  "97",
	"EX Sandstorm":               "100",
	"EX Ruby & Sapphire":         "109",
	"Nintendo Black Star Promos": "",
	// e-Card Series
	"Skyridge":            "144",
	"Aquapolis":           "147",
	"Expedition Base Set": "165",
	// Legendary Collection
	"Legendary Collection": "110",
	// Neo Series
	"Neo Destiny Unlimited":      "105",
	"Neo Detiny 1st Edition":     "105",
	"Neo Revelation Unlimited":   "64",
	"Neo Revelation 1st Edition": "64",
	"Neo Discovery Unlimited":    "75",
	"Neo Discovery 1st Edition":  "75",
	"Neo Genesis Unlimited":      "111",
	"Neo Genesis 1st Edition":    "111",
	"Southern Islands":           "18",
	// Original Series
	"Gym Challenge Unlimited":   "132",
	"Gym Challenge 1st Edition": "132",
	"Gym Heroes Unlimited":      "132",
	"Gym Heroes 1st Edition":    "132",
	"Team Rocket Unlimited":     "82",
	"Team Rocket `1st Edition":  "82",
	"Base Set 2":                "130",
	"Fossil Unlimited":          "62",
	"Fossil 1st Edition":        "62",
	"Jungle Unlimited":          "64",
	"Jungle 1st Edition":        "64",
	"Base Set 4th Print":        "102",
	"Base Set Unlimited":        "102",
	"Base Set Shadowless":       "102",
	"Base Set 1st Edition":      "102",
	"Wizards Black Star Promos": "",
	// McDonald's Promotion
	"McDonald's Collection 2024":       "015",
	"McDonald's Matc Battle 2023":      "015",
	"McDonald's Matc Battle 2022":      "15",
	"McDonald's 25th Anniversary 2021": "25",
	"McDonald's Collection 2019":       "12",
	"McDonald's Collection 2018":       "12",
	"McDonald's Sun & Moon 2017":       "12",
	"McDonald's Collection 2016":       "12",
	"McDonald's Collection 2015":       "12",
	"McDonald's XY 2014":               "12",
	"McDonald's Collection 2013":       "12",
	"McDonald's Collection 2012":       "12",
	"McDonald's Black & White 2011":    "12",
	// // Holiday Sets
	// "2024 Trick or Trade BOOster Bundle": "",
	// "2023 Trick or Trade BOOster Bundle": "",
	// "Holiday Calendar 2025":              "",
	// "2022 Trick or Trade BOOster Bundle": "",
	// "Holiday Calendar 2024":              "",
	// "Holiday Calendar 2023":              "",
	// "Holiday Calendar 2022":              "",
	// // Topps
	// "Topps TV Series 3": "",
	// "Topps TV Series 2": "",
	// "Topps TV Series 1": "",
	// "Topps TV Clear":    "",

	// Japanese
	// Mega Evolution
	"Start Deck 100 Battle Collection": "742",
	"Mega Dream ex":                    "193",
	"Inferno X":                        "080",
	"Mega Symphonia":                   "063",
	"Mega Brave":                       "063",
	// Scarlet & Violet
	"Japanese White Flare":     "086",
	"Japanese Black Bolt":      "086",
	"The Glory of Team Rocket": "098",
	"Hot Wind Arena":           "063",
	"Battle Partners":          "100",
	"Terastal Festival ex":     "187",
	"Super Electric Breaker":   "106",
	"Paradise Dragona":         "064",
	"Stellar Miracle":          "102",
	"Night Wanderer":           "064",
	"Mask of Change":           "101",
	"Crimson Haze":             "066",
	"Cyber Judge":              "071",
	"Wild Force":               "071",
	"Shiny Treasure ex":        "190",
	"Ancient Roar":             "066",
	"Future Flash":             "066",
	"Raging Surf":              "062",
	"Ruler of the Black Flame": "108",
	"Pokemon Card 151":         "165",
	"Clay Burst":               "071",
	"Snow Hazard":              "071",
	"Triplet Beat":             "073",
	"Scarlet ex":               "078",
	"Violet ex":                "078",
	"Scarlet & Violet Promos":  "",
	// Sword & Shield
	"VSTAR Universe":              "172",
	"Paradigm Trigger":            "098",
	"Incandescent Arcana":         "068",
	"Lost Abyss":                  "100",
	"Japanese Pokemon Go":         "071", //same
	"Dark Phantasma":              "071",
	"Space Juggler":               "067",
	"Time Gazer":                  "067",
	"Battle Region":               "067",
	"Star Birth":                  "100",
	"VMAX Climax":                 "184",
	"25th Anniversary Collection": "028",
	"Fusion Arts":                 "100",
	"Blue Sky Stream":             "067",
	"Skyscraping Perfection":      "067",
	"Eevee Heroes":                "069",
	"Jet-Black Spirit":            "070",
	"Silver Lance":                "070",
	"Matchless Fighter":           "070",
	"Rapid Strike Master":         "070",
	"Single Strike Master":        "070",
	"Shiny Star V":                "190",
	"Amazing Volt Tackle":         "100",
	"Legendary Heartbeat":         "076",
	"Infinity Zone":               "100",
	"Explosive Flame Walker":      "070",
	"Rebellion Crash":             "096",
	"VMAX Rising":                 "070",
	"Shield":                      "060",
	"Sword":                       "060",
	"Sword & Shield Promos":       "",
	// Sun & Moon
	"Tag All Stars":                   "173",
	"Alter Genesis":                   "095",
	"Dream League":                    "049",
	"Remix Bout":                      "064",
	"Miracle Twins":                   "094",
	"Great Detective Pikachu":         "024",
	"Sky Legend":                      "054",
	"GG End":                          "054",
	"Double Blaze":                    "095",
	"Full Metal Wall":                 "054",
	"Night Unison":                    "055",
	"Tag Bolt":                        "095",
	"GX Ultra Shiny":                  "150",
	"Dark Order":                      "052",
	"Super-Burst Impact":              "095",
	"Fairy Rise":                      "050",
	"Thunderclap Spark":               "060",
	"Sky-Splitting Charisma":          "096",
	"Champion Road":                   "066",
	"Dragon Storm":                    "053",
	"Japanese Forbidden Light":        "094", //same
	"Ultra Force":                     "050",
	"Ultra Moon":                      "066",
	"Ultra Sun":                       "066",
	"GX Battle Boost":                 "114",
	"Awakened Heroes":                 "050",
	"Ultradimensional Beasts":         "050",
	"Japanese Shining Legends":        "072", //same
	"Darkness that Consumes Light":    "051",
	"To Have Seen the Battle Rainbow": "051",
	"Facing a New Trial":              "049",
	"The Best of XY":                  "171",
	"Alolan Moonlight":                "050",
	"Islands Await You":               "050",
	"Collection Moon":                 "060",
	"Collection Sun":                  "060",
	"Sun & Moon Promos":               "",
	// XY
	"Expansion Pack 20th Anniversary": "087",
	"Cruel Traitor":                   "054",
	"Fever Burst Fighter":             "054",
	"Awakening Psychic King":          "078",
	"Rage of the Broken Heavens":      "080",
	"Blue Shock":                      "059",
	"Red Flash":                       "059",
	"Legendary Shine Collection":      "027",
	"Bandit Ring":                     "081",
	"Emerald Break":                   "078",
	"Gaia Volcano":                    "070",
	"Tidal Storm":                     "070",
	"Phantom Gate":                    "088",
	"Rising Fist":                     "096",
	"Wild Blaze":                      "080",
	"Collection Y":                    "060",
	"Collection X":                    "060",
	"XY Promos":                       "",
	// Black & White
	"EX Battle Boost":      "093",
	"Megalo Cannon":        "076",
	"Shiny Collection":     "020",
	"Spiral Force":         "051",
	"Thunder Knuckle":      "051",
	"Plasma Gale":          "070",
	"Cold Flare":           "059",
	"Freeze Bolt":          "059",
	"Dragon Blade":         "050",
	"Dragon Blast":         "050",
	"Dragon Selection":     "020",
	"Dark Rush":            "069",
	"Hail Blizzard":        "052",
	"Psycho Drive":         "052",
	"Red Collection":       "066",
	"Black Collection":     "053",
	"White Collection":     "053",
	"Black & WHite Promos": "",
	// LEGEND
	"Clash at the Summit":   "080",
	"Lost Link":             "040",
	"Reviving Legends":      "080",
	"SoulSilver Collection": "070",
	"HeartGold Collection":  "070",
	"LEGEND Promos":         "",
	// Platinum
	"Advent of Arceus":         "090",
	"Beat of the Frontier":     "100",
	"Bonds to the End of Time": "090",
	"Galactic's Conquest":      "096",
	"Platinum Promos":          "",
	// Diamond & Pearl
	"Intense Fight in the Destroyed Sky": "092",
	"Cry from the Mysterious":            "",
	"Temple of Anger":                    "",
	"Dawn Dash":                          "",
	"Moonlit Pursuit":                    "",
	"Shining Darkness":                   "",
	"Secret of the Lakes":                "",
	"Space-Time Creation":                "",
	"Diamond & Pearl Promos":             "",
	// PCG Era
	"Offense and Defense of the Furthest Ends": "068",
	"Miracle Crystal":                          "075",
	"Holon Phantom":                            "052",
	"Holon Research Tower":                     "086",
	"Mirage Forest":                            "086",
	"Golden Sky, Silvery Ocean":                "106",
	"Rocket Gang Strikes Back":                 "084",
	"Clash of the Blue Sky":                    "082",
	"Flight of Legends":                        "082",
	"PCG Promos":                               "",
	// Advanced Generation
	"Undone Seal":                 "083",
	"Magma vs Aqua Two Ambitions": "080",
	"Rulers of the Heavens":       "054",
	"Miracle of the Desert":       "053",
	"ADV Expansion Pack":          "055",
	"ADV Promos":                  "",
	// e-Card era
	"Mysterious Mountains":             "088",
	"Split Earth":                      "088",
	"Wind from the Sea":                "087",
	"The Town on No Map":               "092",
	"Expedition Expansion":             "128",
	"Expedition Expansion 1st Edition": "128",
	// VS era
	"Pokemon VS": "141",
	// Neo era
	"Darkness and to Light(Neo Destiny)":       "",
	"Awakening Legends (Neo Revelation)":       "",
	"Crossing the Ruins (Neo Discovery)":       "",
	"Gold Silver to a new World (Neo Genesis)": "",
	"Japanese Southern Islands":                "", //same
	// Original Era
	"Challenge From The Darkness (Gym Challenge)": "",
	"Leader's Stadium (Gym Heroes)":               "",
	"Rocket Gang":                                 "",
	"Msytery of the Fossils":                      "",
	"Pokemon Jungle":                              "",
	"Expansion Pack (Base Set)":                   "",
	// Vending Series
	"Vending Sheet 3 1998": "",
	"Vending Sheet 2 1998": "",
	"Vending Sheet 1 1998": "",
}
