package rarity

var TAGRarities = []string{
	"Prism Star Prism Rare",
	"Special Illustration Rare",
	"Special Art Rare",
	"Illustration Rare",
	"Mega Attack Rare",
	"Mega Ultra Rare",
	"MEGA Ultra Rare",
	"Mega Hyper Rare",
	"Black White Rare",
	"Prism Star Rare",
	"Trainer Rare",
	"Rainbow Rare",
	"Prism Rare",
	"ACE SPEC Rare",
	"Ace Spec Rare",
	"Character Rare",
	"Amazing Rare",
	"Radiant Rare",
	"Shiny Rare",
	"Triple Rare",
	"Art Rare",
	"Ultra Rare",
	"Double Rare",
	"Holo Rare",
	"Super Rare",
	"Secret Rare",
	"Cosmos Holo",
	"Reverse Holo",
	"HYPER RARE",
	"Holo",
	"Common",
}

var CGCRarities = []string{
	"Character Super Rare (Top right)",
	"Character Super Rare (Holo)",
	"Character Super Rare Holo",
	"Reverse Holo Holo Rare",
	"Rainbow Rare Holo Rare Rainbow",
	"Reverse Holo Pokémon League",
	"C. Holo Decidueye-GX Premium Collection",
	"Reverse Holo Regional Championships",
	"Cosmos Holo EB Games",
	"3rd Place League Challenge",
	"(Non-Holo) Forest Shadow Deck",
	"Iron Tide Deck Cr. Ice Holo",
	"Stone Heart Deck Cr. Ice Holo",
	"Prerelease Stamp Holo Rare",
	"Holo Gray Stamp Rare",
	"Radiant Collection Holo",
	"Reverse Holo Rare",
	"Holo Ultra Rare",
	"Super Rare Holo",
	"Ultra Rare Holo",
	"Hyper Rare Holo",
	"Secret Rare Holo",
	"Gray Stamp Energy",
	"(Reverse Holo) Rare",
	"Character Super Rare",
	"Character Rare Holo",
	"Gray Stamp Rare",
	"Holo No Illus. Error Rare",
	"Blue Spot Error",
	"Character Rare",
	"Shadowless Rare",
	"Shadowless Energy",
	"1999-2000 Energy",
	"1999-2000 Rare",
	"Holo Rare",
	"Corrected Symbol",
	"Cosmos Holo (VERY RARE)",
	"Cosmos Holo Forest Force Deck",
	"Polar Frost Deck (Cosmos Holo) Rare",
	"Metal Surge Deck (Cosmos Holo) Rare",
	"Non-Holo",
	"Reverse Holo",
	"(Reverse Holo)",
	"Line Holo",
	"Cosmos Holo",
	"Gray Stamp",
	"Shadowless",
	"PokéTour 1999",
	"1999-2000",
	"Uncommon",
	"Common",
	// "Holo",
}

var BGSRarities = map[string]string{
	"SIR":            "Special Illustration Rare",
	"SAR":            "Special Art Rare",
	"IR":             "Illustration Rare",
	"AR":             "Art Rare",
	"MAR":            "Mega Attack Rare",
	"MUR":            "Mega Ultra Rare",
	"MHR":            "Mega Hyper Rare",
	"BWR":            "Black White Rare",
	"RRR":            "Triple Rare",
	"UR":             "Ultra Rare",
	"RR":             "Double Rare",
	"SR":             "Super Rare",
	"REVERSE HOLO R": "Reverse Holo Rare",
	"REVERSE HOLO C": "Reverse Holo Common",
	"REVERSE HOLO U": "Reverse Holo Uncommon",
	"HOLO R":         "Holo Rare",
	"HOLO U":         "Holo Uncommon",
	"STAMP HOLO":     "Stamp Holo",
	"HOLO":           "Holo",
	// "SR":  "Shiny Rare",
	// "Cosmos Holo",
	// "Holo",
	// "":    "Holo Rare",
	// "Common",
}
