package constant

var IPSet = map[string][]string{
	"popmart": {
		"labubu",
		"skullpanda",
		"dimoo",
		"hirono",
		"molly",
		"crybaby",
		"pucky",
		"hacipupu",
		"twinkle-twinkle",
		"zsiga",
		"space-molly",
		"azura",
		"bunny",
		"pino-jelly",
		"sweet-bean",
		"duckoo",
		"kubo",
		"zoe",
		"instinctoy",
		"peach-riot",
	},
	"miniso": {
		"mini-family",
		"miniso-original-characters",
		"minini",
		"monboo",
		"mr-bone",
		"maltese",
		"wakuku",
		"miniso",
		"sanrio",
		"disney",
		"pixar",
		"marvel",
		"minions",
		"one-piece",
		"minecraft",
		"we-bare-bears",
		"snoopy",
		"harry-potter",
		"lilo-stitch",
		"mickey-mouse",
		"crayon-shin-chan",
		"chiikawa",
		"care-bears",
		"barbie",
		"bt21",
		"teletubbies",
		"tom-jerry",
		"winnie-the-pooh",
		"zootopia",
		"squid-game",
		"super-mario",
		"transformers",
		"jurassic-world",
		"my-little-pony",
		"powerpuff-girls",
	},
	"funco": {
		"pop",
		"bitty-pop",
		"pop-yourself",
		"loungefly",
		"mondo",
		"mystery-minis",
		"funko-soda",
		"funko-plush",
		"funko-action-figures",
	},
	"52toys": {
		"nook",
		"panda-roll",
		"pouka-pouka",
		"cicilu",
		"ninnic",
		"crayon-shin-chan",
		"bob-tim",
		"sleep",
		"lilith",
	},
	"mighty-jaxx": {
		"freenys-hidden-dissectibles",
		"kandy",
		"kandyland",
	},
	"kidrobot": {
		"dunny",
		"munny",
		"labbit",
		"yummy-world",
	},
	"tokidoki": {
		"unicorno",
		"cactus-friends",
		"donutella",
		"mermicorno",
		"moofia",
		"til-death",
		"lumi-and-her-beary-cute-friends",
		"tiger-nation",
	},
	"dreams": {
		"sonny-angel",
		"smiski",
		"hippers",
		"funbarus",
	},
	"medicom-toy": {
		"real-action-heroes",
		"project-bm",
		"ultimate-unison",
		"be@rbrick",
		"mafex",
		"kubrick",
		"vinyl-collectible-dolls",
		"ultra-detail-figure",
		"perfect-posing-products",
		"miracle-action-figure",
		"pre-assembled-collection",
	},
}
